myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('smokingshop/', include('smokingshop.urls')),
    path('',  RedirectView.as_view(url='/smokingshop/')),
]

smokingshop/urls.py
from django.urls import path
from . import views

app_name = 'smokingshop'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

smokingshop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
#ここまでがカテゴリのモデル

class Shop(models.Model):
    name = models.CharField('店舗名', max_length=255)
    Address = models.CharField('住所入力', max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey( #←ここから
        Category,  verbose_name='ジャンル',               #カテゴリとショップモデルを関連付けしてる項目ショップからカテゴリを参照しているのでカテゴリから記述する必要がある
        on_delete=models.PROTECT,  #category変数はマイグレーションすると勝手にcategoryIDというカラムを作成してくれる
    )                             #←ここまで
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('smokingshop:detail', kwargs={'pk': self.pk})

smokingshop/forms.py
from django import forms

class SearchForm(forms.Form):
    keyword = forms.CharField(label='検索', max_length=100)

smokingshop/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Shop

class IndexView(generic.ListView):
    model = Shop

class DetailView(generic.DetailView):
    model = Shop

class CreateView(generic.edit.CreateView):
    model = Shop
    fields = '__all__' #全てのカラムを入力できるフォームになる

class UpdateView(generic.edit.UpdateView):
    model = Shop
    fields = '__all__' #全てのカラムを入力できるフォームになる

class DeleteView(generic.edit.DeleteView):
    model = Shop
    success_url = reverse_lazy('smokingshop:index')

smokingshop/templates/smokingshop/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <title>Smokingshop</title>
        <style>body {padding-top: 80px;}</style>
    </head>
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "smokingshop:index" %}'>Smokingshop</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

smokingshop/templates/smokingshop/shop_confirm_delete.html
{% extends './base.html' %}
{% block content %}

<h1>お店情報の削除</h1>
<p>'{{ object.name }}'を削除しますか?</p>
<form action='' method='post'>{% csrf_token %}
    <button type='submit' class='submit delete'>削除する</button>
</form>

<div>
    <p><a href='JavaScript:history.back()'>&lt; 戻る</a></p>
</div>

{% endblock %}

smokingshop/templates/smokingshop/shop_detail.html
{% extends './base.html' %}
{% block content %}

<h1>{{ shop.name }}</h1>
<div>
    <p>{{ shop.category.name }}</p>
    <p>{{ shop.address }}</p>
</div>
<iframe id='map'
    src='https://www.google.com/maps/embed/v1/place?key=AIzaSyCumg3adan6ibeC0MKTmntTpYnxwRbOSOc&q={{ shop.Address }}'
    width='100%'
    height='320'
    frameborder='0'>
</iframe>
<div>
    <a href='{% url "smokingshop:index" %}'>一覧</a>
    <a href='{% url "smokingshop:update" shop.pk %}'>編集</a> |
    <a href='{% url "smokingshop:delete" shop.pk %}'>削除</a>
</div>

{% endblock %}

smokingshop/templates/smokingshop/shop_form.html
{% extends './base.html' %}
{% block content %}

<h1>お店情報の{{ object|yesno:'更新,追加'}}</h1>

<form action='' method='post'>{% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='submit'>{{ object|yesno:'更新,作成'}}</button>
</form>
<div>
    <a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}

smokingshop/templates/smokingshop/shop_list.html
{% extends './base.html' %}
{% block content %}

    <h1>喫煙できるお店一覧</h1>
    <table class='table table-striped table-hover'>
        <tr>
            <th>店名</th><th>ジャンル</th><th>住所</th>
        </tr>
        {% for shop in object_list %}
        <tr>
            <td><a href='{% url "smokingshop:detail" shop.pk %}'>{{ shop.name }}</a></td>
            <td>{{ shop.category.name }}</td>
            <td>{{ shop.Address }}</td>
        </tr>
        {% endfor %}
    </table>
    <div>
        <a href='{% url "smokingshop:create" %}'>お店を登録する</a>
    </div>
{% endblock %}